language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - export BOTO_CONFIG=/dev/null

install:
  - pip install --editable . # Install it self
  - pip install -r requirements-test.txt # Install test dependencies
  - pip install codecov # Install coveralls

script:
  - pytest tests --cov=s3iotools # Run unittest

notifications:
  email: false # Mute email notification

after_success:
  - codecov # travis-ci will transfer data to codecov after success
